import '@/styles/background.scss';
import type { Metadata } from 'next';
import 'primeicons/primeicons.css';
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/primereact.min.css';
import 'primereact/resources/themes/lara-dark-blue/theme.css';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className='gradient-bg'>
                <PrimeReactProvider value={{ ripple: true }}>{children}</PrimeReactProvider>
                {/* FIXME: hover issues */}
                <div className='gradients-container'>
                    <div className='g1'></div>
                    <div className='g2'></div>
                    <div className='g3'></div>
                    <div className='g4'></div>
                    <div className='g5'></div>
                </div>
            </body>
        </html>
    );
}
